### ISSUE TITLE
Conversion script not work with new release

### ISSUE THREAD

**Issue by zell180** [carlsonsantana/convert_rpggame_to_android#1]
Hi, conversion script not work with new release of EasyRPG based on gradle. You should kindly fix it?

**Comment by carlsonsantana** [comment]
I will try.

**Comment by carlsonsantana** [comment]
Do you use the new version?

**Comment by zell180** [comment]
Thank you very much ❤️

**Comment by zell180** [comment]
I'm using the last version of conversion script and the last version of
Easyrpg player master repo

Il Sab 27 Mar 2021, 20:25 Carlson Santana Cruz ***@***.***>
ha scritto:

**Comment by carlsonsantana** [comment]
The problem with running the script is due to the NYI's that changed the location. In addition it was verified that the build now depends on the gtk-doc package and even though the build is running successfully, the application still closes immediately after executing, to solve this problem I commented the lines that change the package name.

I will try to fix the problem with the change of package name, but I think that you can test your game with these changes. You will need delete `buildscripts/android/Player` folder and execute `5_build_android_port.sh` before run the script.

**Comment by zell180** [comment]
Ok works but package keep org.easyrpg.player structure

**Comment by carlsonsantana** [comment]
Finally I discover the reason of issues with changing the package name and fix it, now you can change the package name.

**Comment by Ghabry** [comment]
Imo all this jni moving and renaming is quite ugly.
But I'm pretty sure this is solvable.
I want to rework the app until December this year because Google requires some significant changes (storage framework enforced), so will also take a look at this. 👍

**Comment by carlsonsantana** [comment]
I'm closing the issue, because the problems are solved and not receive more comments about new issues.
